# Generated by Django 5.1.7 on 2025-03-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topwinz_app', '0002_raffle_raffleentry_delete_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
